language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --configuration tests/phpunit.xml.dist tests/
